In [ ]:
#1)heap,hash,graph(prim,kruskal) interface tanımlanacak.
#2)QR decomposition of a Matris

In [ ]:
#1)heap,hash,graph(prim,kruskal) interface tanımlanacak.

#Heap İnterface  
    
    The ADT Heap

Interface used for implementation of
maxheap

 public interface MaxHeapinterface
  public void add(Comparable newEntry);
  public Comparable removeMax();
  public Comparable getMax();
  public boolean isEmpty();
  public int getSize();
  public void clear();
 } I/ end MaxHeapinterface


#Hash İnterface


"hash" ADT: interface

#ifndef HASH_H
#define HASH H

typedef struct hash *hash;

hash newHash ();
hash newHash2 (double lf);
void insert (hash h, poly key, poly value);
poly lookup (hash h, poly key);
void delete (hash h, poly key);

#endif


#Graph İnterface


public interface Graph {
    public Graph createGraph(String name, int ID, Node[] nodes, Edge[] edges, Node root);
    public String getName();
    public Edge[] getEdges();
    public void addEdge(Edge e);
    public Edge getEdge(String name, int ID);
    public void removeEdge(Edge e);
    public Node[] getNodes();
    public void addNode(Node n);
    public Node getNode(String name, int ID);
    public void removeNode(Node n);
    public void setRoot(Node n);
    public Node getRoot();  
    public boolean isTree();        <= optional!
    public String toString();

In [1]:
#2)QR decomposition of a Matris

import numpy as np
 
def qr(A):
    m, n = A.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        H = np.eye(m)
        H[i:, i:] = make_householder(A[i:, i])
        Q = np.dot(Q, H)
        A = np.dot(H, A)
    return Q, A
 
def make_householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H
 
# task 1: show qr decomp of wp example
a = np.array(((
    (12, -51,   4),
    ( 6, 167, -68),
    (-4,  24, -41),
)))
 
q, r = qr(a)
print('q:\n', q.round(6))
print('r:\n', r.round(6))
 
# task 2: use qr decomp for polynomial regression example
def polyfit(x, y, n):
    return lsqr(x[:, None]**np.arange(n + 1), y.T)
 
def lsqr(a, b):
    q, r = qr(a)
    _, n = r.shape
    return np.linalg.solve(r[:n, :], np.dot(q.T, b)[:n])
 
x = np.array((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
y = np.array((1, 6, 17, 34, 57, 86, 121, 162, 209, 262, 321))
 
print('\npolyfit:\n', polyfit(x, y, 2))

q:
 [[-0.857143  0.394286  0.331429]
 [-0.428571 -0.902857 -0.034286]
 [ 0.285714 -0.171429  0.942857]]
r:
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.   -0.  -35.]]

polyfit:
 [ 1.  2.  3.]
